/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transmitter_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(535a3bb16d3daba47a5a455e5cef89ba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/NTSC/transmitter_c.h>
// pydoc.h is automatically generated in the build directory
#include <transmitter_c_pydoc.h>

void bind_transmitter_c(py::module& m)
{

    using transmitter_c    = ::gr::NTSC::transmitter_c;


    py::class_<transmitter_c, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<transmitter_c>>(m, "transmitter_c", D(transmitter_c))

        .def(py::init(&transmitter_c::make),
           py::arg("samp_rate"),
           D(transmitter_c,make)
        )
        



        ;




}








